TBPL_TESTS = {
    'SVG No Chrome': {'testname': 'tsvgx', 'wikiname': 'tsvg.2C_tsvgx', 'jobname': 'svgr'},
    'SVG Row Major': {'testname': 'tsvgx', 'wikiname': 'tsvg.2C_tsvgx', 'jobname': 'svgr'},
    'SVG, Opacity Row Major': {'testname': 'tsvgr_opacity', 'wikiname': 'tsvg-opacity', 'jobname': 'svgr'},
    'Dromaeo (DOM)': {'testname': 'dromaeo_dom', 'wikiname': 'Dromaeo_DOM', 'jobname': 'dromaeojs'},
    'Dromaeo (CSS)': {'testname': 'dromaeo_css', 'wikiname': 'Dromaeo_CSS', 'jobname': 'dromaeojs'},
    'Kraken Benchmark': {'testname': 'kraken', 'wikiname': 'kraken', 'jobname': 'dromaeojs'},
    'V8': {'testname': 'v8_7', 'wikiname': 'V8.2C_version_7', 'jobname': 'dromaeojs'},
    'V8 Version 7': {'testname': 'v8_7', 'wikiname': 'V8.2C_version_7', 'jobname': 'dromaeojs'},
    'V8 version 7': {'testname': 'v8_7', 'wikiname': 'V8.2C_version_7', 'jobname': 'dromaeojs'},
    'Paint': {'testname': 'tpaint', 'wikiname': 'tpaint', 'jobname': 'other'},
    'tscroll Row Major': {'testname': 'tscrollx', 'wikiname': 'tscroll.2C_tscrollx', 'jobname': 'svgr'},
    'TResize': {'testname': 'tresize', 'wikiname': 'tresize', 'jobname': 'chromez'},
    'Tp5 Optimized': {'testname': 'tp5o', 'wikiname': 'tp5', 'jobname': 'tp5o'},
    'Tp5 Optimized (Private Bytes)': {'testname': 'tp5o Private Bytes', 'wikiname': 'tp5', 'jobname': 'tp5o'},
    'Tp5 Optimized (Main RSS)': {'testname': 'tp5o Main_RSS', 'wikiname': 'tp5', 'jobname': 'tp5o'},
    'Tp5 Optimized (Content RSS)': {'testname': 'tp5o', 'wikiname': 'tp5', 'jobname': 'tp5o'},
    'Tp5 Optimized (%CPU)': {'testname': 'tp5o', 'wikiname': 'tp5', 'jobname': 'tp5o'},
    'Tp5 No Network Row major MozAfterPaint (Main Startup File I/O Bytes)': {'testname': 'tp5n', 'wikiname': 'xperf', 'jobname': 'xperf'},
    'Tp5 No Network Row Major MozAfterPaint (Non-Main Startup File IO Bytes)': {'testname': 'tp5n', 'wikiname': 'xperf', 'jobname': 'xperf'},
    'Tp5 No Network Row Major MozAfterPaint (Non-Main Normal Network IO Bytes)': {'testname': 'tp5n', 'wikiname': 'xperf', 'jobname': 'xperf'},
    'Tp5 No Network Row Major MozAfterPaint (Main Normal File IO Bytes)': {'testname': 'tp5n', 'wikiname': 'xperf', 'jobname': 'xperf'},
    'Tp5 No Network Row Major MozAfterPaint (Main Startup File IO Bytes)': {'testname': 'tp5n', 'wikiname': 'xperf', 'jobname': 'xperf'},
    'Tp5 No Network Row Major MozAfterPaint (Non-Main Normal File IO Bytes)': {'testname': 'tp5n', 'wikiname': 'xperf', 'jobname': 'xperf'},
    'Tp5 Optimized (Modified Page List Bytes)': {'testname': 'tp5o', 'wikiname': 'tp5', 'jobname': 'tp5o'},
    'Tp5 Optimized Responsiveness': {'testname': 'tp5o', 'wikiname': 'tp5', 'jobname': 'tp5o'},
    'Tp5 Optimized MozAfterPaint': {'testname': 'tp5o', 'wikiname': 'tp5', 'jobname': 'tp5o'},
    'a11y Row Major MozAfterPaint': {'testname': 'a11yr', 'wikiname': 'a11y', 'jobname': 'other'},
    'Tp4 Mobile': {'testname': 'tp4m', 'wikiname': 'tp5', 'jobname': 'remote-tp4m_nochrome'},
    'LibXUL Memory during link': {'testname': '', 'wikiname': '', 'jobname': ''},
    'Ts, Paint': {'testname': 'ts_paint', 'wikiname': 'ts_paint', 'jobname': 'other'},
    'Robocop Pan Benchmark': {'testname': 'trobopan', 'wikiname': 'robocop', 'jobname': 'remote-trobopan'},
    'Robocop Database Benchmark': {'testname': '', 'wikiname': 'robocop', 'jobname': 'remote-troboprovider'},
    'Robocop Checkerboarding No Snapshot Benchmark': {'testname': 'tcheckerboard', 'wikiname': 'robocop', 'jobname': 'remote-trobocheck2'},
    'Robocop Checkerboarding Real User Benchmark': {'testname': 'tcheck2', 'wikiname': 'robocop', 'jobname': 'remote-trobocheck2'},
    'Customization Animation Tests': {'testname': 'cart', 'wikiname': 'TART.2FCART', 'jobname': 'svgr'},
    'Latency Performance Tests': {'testname': '', 'wikiname': '', 'jobname': ''},
    'Tab Animation Test, NoChrome': {'testname': 'tart', 'wikiname': 'TART.2FCART', 'jobname': 'svgr'},
    'Tab Animation Test': {'testname': 'tart', 'wikiname': 'TART.2FCART', 'jobname': 'svgr'},
    'Canvasmark, NoChrome': {'testname': 'tcanvasmark', 'wikiname': 'CanvasMark', 'jobname': 'chromez'},
    'Canvasmark': {'testname': 'tcanvasmark', 'wikiname': 'CanvasMark', 'jobname': 'chromez'},
    'CanvasMark, NoChrome': {'testname': 'tcanvasmark', 'wikiname': 'CanvasMark', 'jobname': 'chromez'},
    'CanvasMark': {'testname': 'tcanvasmark', 'wikiname': 'CanvasMark', 'jobname': 'chromez'},
    'Tab Animation Test, NoChrome': {'testname': 'tart', 'wikiname': 'TART.2FCART', 'jobname': 'svgr'},
    'tscroll-ASAP': {'testname': 'tscrollx', 'wikiname': 'tscroll.2C_tscrollx', 'jobname': 'svgr'},
    'SVG-ASAP, NoChrome': {'testname': 'tsvgx', 'wikiname': 'tsvg.2C_tsvgx', 'jobname': 'svgr'},
    'SVG-ASAP': {'testname': 'tsvgx', 'wikiname': 'tsvg.2C_tsvgx', 'jobname': 'svgr'},
    'tscroll-ASAP MozAfterPaint': {'testname': 'tscrollx', 'wikiname': 'tscroll.2C_tscrollx', 'jobname': 'svgr'},
    'Session Restore no Auto Restore Test': {'testname': 'sessionrestore_no_auto_restore', 'wikiname': 'sessionrestore.2Fsessionrestore_no_auto_restore', 'jobname': 'other'},
    'Session Restore Test': {'testname': 'sessionrestore', 'wikiname': 'sessionrestore.2Fsessionrestore_no_auto_restore', 'jobname': 'other'},
    'WebRTC Media Performance Tests': {'testname': 'media_tests', 'wikiname': 'media_tests', 'jobname': 'other'},
    'TP5 Scroll': {'testname': 'tp5o_scroll', 'wikiname': 'tp5o_scroll', 'jobname': 'g1'},
    'WEBGL Terrain': {'testname': 'glterrain', 'wikiname': 'glterrain', 'jobname': 'g1'},
    'Devtools At Maximum Performance': {'testname': 'damp', 'wikiname': 'DAMP', 'jobname': 'g2'},
    'Tp5 Optimized (XRes)': {'testname': 'tp5o', 'wikiname': 'tp5o', 'jobname': 'tp'},
    'Number of Constructors': {'testname': 'build', 'wikiname': 'Other_data', 'jobname': 'undefined'},
    'Tp5 No Network Row Major MozAfterPaint (Non-Main Normal File IO Bytes)': {'testname': 'xperf', 'wikiname': 'xperf', 'jobname': 'xperf'},
    'Talos Page Switch': {'testname': 'tps', 'wikiname': 'tps', 'jobname': 'g2'}
}

PLATFORMS = {'ubuntu hw 12.04 x64': 'linux64',
             'ubuntu hw 12.04 x64 (e10s)': 'linux64-e10s',
             'winnt 6.2 x64': 'windows8-64',
             'winnt 6.2 x64 (e10s)': 'windows8-64-e10s',
             'ubuntu hw 12.04': 'linux32',
             'ubuntu hw 12.04 (e10s)': 'linux32-e10s',
             'winnt 6.1 (ix)': 'windows7-32',
             'winnt 6.1 (ix) (e10s)': 'windows7-32-e10s',
             'winnt 5.1 (ix)': 'windowsxp',
             'winnt 5.1 (e10s)': 'windowsxp-e10s',
             'macosx 10.6 (rev4)': 'osx10.6',
             'macosx 10.8': 'osx10.8',
             'macosx 10.10': 'osx-10-10',
             'macosx 10.10 (e10s)': 'osx-10-10-e10s',
             'android 4.0.4': 'android-4-0-armv7-api11'
             }

